name: tables-detr2
channels:
 - conda-forge
 - pytorch
 - defaults
dependencies:
  - python
  - pip
  - pytorch==1.5.0
  - cudatoolkit
  - torchvision==0.6.0
  - pandas
  - scikit-learn
  - tqdm
  - Cython
  - matplotlib
  - numpy
  - pycocotools
  - pip:
    - scikit-image
    - scipy
    - PyMuPDF==1.16.14
